#!/bin/sh
# @(#)$KimmoSuominen$
#
# Characterize redirects: collection fallback (302) and
# extra-path-component canonicalization (308).
#
# 20260809  Kimmo Suominen
#

set -eu

CDPATH=

TESTS_DIR=$(cd "$(dirname "${0}")/.." && pwd)
. "${TESTS_DIR}/lib.sh"

test_init

# A release that has moved on to its branch collection: the
# collection directory NetBSD-9.3 does not exist but
# NetBSD-9.x-BRANCH does, so the request 302s there.
run_cgi /NetBSD-9.3/ls.1

assert_exit 0
assert_header '^Status: 302 Found$'
assert_header '^Location: https://man.netbsd.org/NetBSD-9.x-BRANCH/ls.1$'
assert_header '^Cache-Control: public, max-age=86400$'
assert_header '^X-Accel-Expires: 86400$'
assert_header '^Surrogate-Control: max-age=604800$'
assert_no_header '^Last-Modified:'
assert_body 'Goto:'

# Extra path components collapse into ARCH/COMMAND with a
# permanent redirect to the canonical URL.
run_cgi /i386/i386/ls.1

assert_exit 0
assert_header '^Status: 308 Permanent Redirect$'
assert_header '^Location: https://man.netbsd.org/i386/ls.1$'
assert_header '^Cache-Control: public, max-age=86400$'
assert_header '^X-Accel-Expires: 2592000$'
assert_header '^Surrogate-Control: max-age=2592000$'

test_done
