#!/bin/sh
# Man-cgi : a Common Gateway Interface which converts the output of
#           the "man" command to HTML
#
# Author  : Panagiotis J. Christias <christia@theseas.ntua.gr>
#
# Usage   : it goes in the /cgi-bin/ directory. When called without 
#           arguments (https://www-server/cgi-bin/man-cgi) it outputs a
#           "Front Page" with a section list and query form. When called
#           with arguments, the first argument is the topic (e.g. ls)
#           and the second argument (optional) is the section to look in.
#
#           http://www.ntua.gr/~christia/man-cgi.html
#           XXX: Dead link detected 2017-04-15
#
#           Examples:
#               http://www.ntua.gr/cgi-bin/man-cgi?ls
#               http://www.ntua.gr/cgi-bin/man-cgi?sleep+3
#
# Notice  : Man-cgi uses the following two images, you may want to get them
#           and put them in your w3 server:
#               http://www.ntua.gr/images/doty.gif
#               http://www.ntua.gr/images/pages.gif
#
# History :
#   7.0     Handle multicharacter sections (e.g. intro(9lua)).
#   1.15    Multiple blank lines are supressed.
#   1.14    Man-cgi now recognizes cross-references that
#           contain periods (e.g. foo.foo(3)).
#   1.13    Really fixed problems occuring in pages which used
#           multi-overstrike for emboldening (hopefully).
#   1.12    Fixed problems occuring in pages which used multi-overstrike
#           for emboldening. Now Man-cgi works any number of overstrike.
#   1.11    Fixed problem with hyphenated cross-references.
#   1.10 and earlier, no history at that time...
#
# Last update: Sat Apr 15 2017
#

### CONFIGURATION SECTION : change the following variables to fit your needs ###

# The HTTPD server may not pass the enviroment variables to the script.
# You should add your system path here :
export PATH
PATH=/usr/local/bin:/bin:/usr/bin

# The same for the man path here :
#export MANPATH
#MANPATH=/usr/local/man:/usr/local/X/man:/usr/share/man:/usr/local/gnu/man

# Character set ISO-8859-1
export LC_CTYPE
LC_CTYPE=en_US.ISO8859-1
CHARSET=windows-1252

# OS details
OSARCH=$(uname -m)
OSNAME=$(uname -s)
OSREL=$(uname -r)

# Man page collections
MANROOT=/p/netbsd/www/man

# The URL of the two images :
DOT=/s/man-dot.gif
PAGES=/s/pages.gif

# Last modified is NetBSD-current build retrieval date
LASTMODFILE="$MANROOT/NetBSD-current/build"

### END OF CONFIGURATION SECTION ###############################################

canonical_url()
{
    local arch coll port section

    case "${REQUEST_SCHEME:-http}" in
    https)
	case "${SERVER_PORT:-443}" in
	443)	port=;;
	*)	port=":${SERVER_PORT}";;
	esac
	;;
    *)
	case "${SERVER_PORT:-80}" in
	80)	port=;;
	*)	port=":${SERVER_PORT}";;
	esac
	;;
    esac

    case "${COLL}" in
    DEFAULT|"${DEFAULT_COLLECTION}"|"")
	coll=
	;;
    *)
	coll="${COLL}"
	;;
    esac

    case "${ARCH}" in
    DEFAULT|"${DEFAULT_ARCH}"|"")
	arch=
	;;
    *)
	arch="${ARCH}"
	;;
    esac

    case "$SECTION" in
    ANY|"")
	section=
	;;
    *)
	section="${SECTION}"
	;;
    esac

    case "${COMMAND}" in
    "")
	echo "${REQUEST_SCHEME-:http}://${SERVER_NAME}${port}${SCRIPT_NAME}?+${section}${arch:+.$arch}+${coll}"
	;;
    *)
	# XXX: We should probably have some configurable prefix, too.
	echo "${REQUEST_SCHEME-:http}://${SERVER_NAME}${port}${coll:+/$coll}${arch:+/$arch}/${COMMAND}${section:+.$section}"
	;;
    esac
}

rel_canonical_url()
{
    # Assumptions:
    # - Also serving over https, so advertise it as canonical
    # - Only using non-standard ports for development, so
    #   they are not seen by search engines

    canonical_url \
    | sed -e "
	s/^http:/https:/
	s,:[1-9][0-9]*/,/,
	s,/${ARCH}/,/${CANONICAL_ARCH:-$ARCH}/,
	s,/NONE/,/,
    "
}

list_archs()
{
    case "${DEFAULT_ARCH}" in
    "")
	echo DEFAULT
	;;
    esac
    echo NONE
    cat "${MANROOT}/archlist"
}

list_collections()
{
    case "${DEFAULT_COLLECTION}" in
    "")
	echo DEFAULT
	;;
    esac
    cat "${MANROOT}/colllist"
}

case "$PATH_INFO" in
''|/)
    if [ $# -lt 2 ]
    then
	QS="$(
	    echo "${1:-${QUERY_STRING:-}}" \
	    | sed \
		-e 's/%20/+/g' \
		-e 's/%2B/+/g' \
		-e 's/%2b/+/g' \
		-e 's/=$//' \
		;
	)"
	OIFS="$IFS"
	IFS="${OIFS}+"
	set -- ${QS}
	IFS="${OIFS}"
    fi

    COMMAND="${1}"
    SECTION="${2:-ANY}"
    COLL="${3:-DEFAULT}"
    ARCH=DEFAULT

    case "${COMMAND}" in
    "")
	;;
    *)
	need_redirect=true
	;;
    esac
    ;;
*)
    OIFS="$IFS"
    IFS="${OIFS}/"
    set -- ${PATH_INFO}
    IFS="${OIFS}"
    shift

    SECTION=ANY
    COLL=DEFAULT
    ARCH=DEFAULT

    case ${#} in
    1)
	COMMAND="${1}"
	;;
    2)
	COMMAND="${2}"
	case "${1}" in
	[A-Z]*)
	    COLL="${1}"
	    ;;
	*)
	    ARCH="${1}"
	    ;;
	esac
	;;
    *)
	COLL="${1}"
	while [ ${#} -gt 3 ]
	do
	    need_redirect=true
	    shift
	done
	ARCH="${2}"
	COMMAND="${3}"
	;;
    esac
    ;;
esac

#case "$PATH_INFO" in
#/apropos)
#    MANPARAM="-k"
#    echo 'X-Robots-Tag: noindex'
#    ;;
#esac

set -- $COMMAND
COMMAND="$1"
set -- $SECTION
SECTION="$1"
set -- $COLL
COLL="$1"

echo "Content-Type: text/html; charset=$CHARSET"

case "$REQUEST_METHOD" in
POST)
    read a
    OIFS="$IFS"
    IFS="${OIFS}&+"
    set -- $a
    IFS="${OIFS}"

    for i
    do
	case "$i" in
	arch=*)
	    ARCH="${i#arch=}"
	    ;;
	coll=*)
	    COLL="${i#coll=}"
	    ;;
	command=*)
	    COMMAND="$(echo "$i" | sed -e 's/command=//' -e 's,%2F,/,gi')"
	    ;;
	section=*)
	    SECTION="${i#section=}"
	    ;;
	esac
    done

    ME="$(canonical_url)"

    echo 'Status: 303 See Other'
    echo "Location: $ME"
    echo
    echo 'Goto: <a href="'"$ME"'">'"$ME"'</a>'

    exit 0
    ;;
esac

case "$SECTION" in
.*)
    ARCH="${SECTION#.}"
    SECTION=
    ;;
*.*)
    ARCH="${SECTION##*.}"
    SECTION="${SECTION%%.*}"
    ;;
esac

case "$SECTION" in
ANY)
    SECTION=
    ;;
esac

case "$COMMAND" in
*.[1-9]|*.3f|*.[39]lua)
    SECTION="${COMMAND##*.}"
    COMMAND="${COMMAND%.*}"
    ;;
esac

case "$COMMAND" in
*/*)
    ARCH="${COMMAND%/*}"
    COMMAND="${COMMAND##*/}"
    ;;
esac

case "${DEFAULT_ARCH}" in
"")
    ;;
*)
    case "${ARCH}" in
    DEFAULT|"")
	ARCH="${DEFAULT_ARCH}"
	;;
    esac
    ;;
esac

case "$ARCH" in
DEFAULT|"")
    ARCH=
    ;;
*)
    export MACHINE
    MACHINE="$ARCH"
    ;;
esac

case "${ARCH}" in
"${DEFAULT_ARCH}")
    ARCH=
    ;;
esac

case "${DEFAULT_COLLECTION}" in
"")
    ;;
*)
    case "${COLL}" in
    DEFAULT|"")
	COLL="${DEFAULT_COLLECTION}"
	;;
    esac
    ;;
esac

case "${COLL}" in
DEFAULT|"")
    COLL=
    ;;
*)
    COLL=$(echo "$COLL" | tr -c -d '[-.A-Za-z0-9]')
    if [ ! -d "${MANROOT}/${COLL}" ]
    then
	case "${COLL}" in
	*-[1-9][0-9].0)
	    NCOLL="${COLL%%-*}-current"
	    if [ -d "${MANROOT}/${NCOLL}" ]
	    then
		COLL="${NCOLL}"
		ME="$(canonical_url)"

		echo 'Status: 302 Found'
		echo "Location: $ME"
		echo
		echo 'Goto: <a href="'"$ME"'">'"$ME"'</a>'

		exit 0
	    fi
	    ;;
	*-[1-9].*|*-[1-9][0-9].*)
	    MINOR="$((${COLL##*.} + 0))"
	    case "${MINOR}" in
	    0)
		;;
	    *)
		NCOLL="${COLL%.*}.$((${MINOR} - 1))-STABLE"
		if [ -d "${MANROOT}/${NCOLL}" ]
		then
		    COLL="${NCOLL}"
		    ME="$(canonical_url)"

		    echo 'Status: 302 Found'
		    echo "Location: $ME"
		    echo
		    echo 'Goto: <a href="'"$ME"'">'"$ME"'</a>'

		    exit 0
		fi
		;;
	    esac
	    ;;
	esac
    fi
    export MANPATH
    MANPATH="${MANROOT}/${COLL}"
    export GROFF_TMAC_PATH
    GROFF_TMAC_PATH="${MANPATH}/tmac"
    CNAME="${COLL%%-*}"
    CREL="${COLL#*-}"
    ;;
esac

case "${COLL}" in
"${DEFAULT_COLLECTION}")
    COLL=
    ;;
esac

if ${need_redirect:-false}
then
    ME="$(canonical_url)"

    echo 'Status: 308 Permanent Redirect'
    echo "Location: $ME"
    echo
    echo 'Goto: <a href="'"$ME"'">'"$ME"'</a>'

    exit 0
fi

# 1 hour
EXPSECS=3600

if [ "$COMMAND" != "" ]
then
    case "$SECTION" in
    "")
	if [ "$MANPARAM" = "" ]
	then
	    LASTMODFILE=$(
		man -C "$MANROOT/man.conf" -w -- "$COMMAND" 2>/dev/null
	    )
	    notfound=$?
	fi
	;;
    *)
	LASTMODFILE=$(
	    man -C "$MANROOT/man.conf" -w -- "$SECTION" "$COMMAND" 2>/dev/null
	)
	notfound=$?
	;;
    esac

    if [ ${notfound:-0} -ne 0 ]
    then
	echo 'Status: 404 Not Found'
	# 10 minutes
	EXPSECS=600
    else
	case "${COLL}" in
	*-current|*-STABLE)
	    # 8 hours
	    EXPSECS=28800
	    ;;
	*)
	    # 16 days
	    EXPSECS=1382400
	    ;;
	esac
    fi
fi

LASTMODFILE="$(echo "$LASTMODFILE" | sed -e 1q)"

case "${LASTMODFILE}" in
*/build)
    ;;
*)
    # XXX: This breaks when # DEFAULT_COLLECTION is not set
    # and the DEFAULT collection is used for system pages.

    CANONICAL_ARCH="${LASTMODFILE##${MANROOT}/}"
    CANONICAL_ARCH="${CANONICAL_ARCH#*/}"
    CANONICAL_ARCH="${CANONICAL_ARCH#*/}"
    case "${CANONICAL_ARCH}" in
    */*/*)
	# Too many!
	CANONICAL_ARCH=
	;;
    */*)
	CANONICAL_ARCH="${CANONICAL_ARCH%/*}"
	;;
    *)
	CANONICAL_ARCH=NONE
	;;
    esac

    case "${SECTION}" in
    "")
	SECTION="${LASTMODFILE##*.}"
	case "${SECTION}" in
	"")
	    ;;
	[1-9]|3f|[39]lua)
	    ME="$(canonical_url)"

	    echo 'Status: 303 See Other'
	    echo "Location: $ME"
	    echo
	    echo 'Goto: <a href="'"$ME"'">'"$ME"'</a>'

	    exit 0
	    ;;
	*)
	    SECTION=
	    ;;
	esac
	;;
    esac
    ;;
esac

if [ -f "$LASTMODFILE" ]
then
    eval $(stat -s "$LASTMODFILE")
    LASTMOD=$(date -u -r "$st_mtime" '+%a, %d %b %Y %H:%M:%S GMT')
    if [ -n "$LASTMOD" ]
    then
	echo "Last-Modified: $LASTMOD"
    fi
fi

EXPDATE=$(($(date '+%s') + $EXPSECS))
EXPIRES=$(date -u -r "$EXPDATE" '+%a, %d %b %Y %H:%M:%S GMT')

echo "Expires: $EXPIRES"
echo "Cache-Control: public, max-age=$EXPSECS"

# End of headers
cat <<END

<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=$CHARSET">
<style type="text/css">
<!--
body { background-color: #ffffff; color: #000000; font-size: 12pt; margin: 2em; }
@media screen {
    body { background-color: #f0f0f0; }
}
a:link, b.section a:visited { color: #0000f0; }
a:visited { color: #6000c0; }
@media screen and (prefers-color-scheme: dark) {
    body { background-color: #000000; color: #c0c0c0; }
    a:link, b.section a:visited { color: #90c0f0; }
    a:visited { color: #c060c0; }
}
table { padding: 0; }
th, td { border: 0; padding: 0; }
.intro th, .intro td { padding-left: 1em; padding-top: 3px; }
b.section { font-size: 14pt; }
b.section a { text-decoration: none; }
.small { font-size: 10pt; }
div.queryform input, div.queryform select { width: 100%; }
body, input, select { font-family: Roboto, sans-serif; }
code, pre, tt { font-family: 'Roboto Mono', monospace; }
@media print {
    div.queryform { display: none; }
    a:link, a:visited, b.section a:visited { color: #000000; }
}
-->
</style>
END

if [ "$COMMAND" != "" ]
then
    cat <<END
<title>$COMMAND${SECTION:+($SECTION)} - ${CNAME:-$OSNAME} Manual Pages</title>
<link rel="shortcut icon" href="/s/${CNAME:-$OSNAME}.ico" type="image/x-icon">
END
    tr -d \\n <<END
<link href="https://fonts.googleapis.com/css2
?family=Roboto:ital,wght@0,400;0,700;1,400;1,700
&family=Roboto+Mono:ital,wght@0,400;0,700;1,400;1,700
&display=swap" rel="stylesheet">
END
    echo

    if [ ${notfound:-0} -eq 0 ]
    then
	if [ "$MANPARAM" = "" ]
	then
	    cat <<END
<link rel="canonical" href="$(rel_canonical_url)">
END
	fi
    fi

    cat <<END
</head>
<body>
END

    if [ ${notfound:-0} -eq 0 ]
    then
	echo "<pre>"
	case "$SECTION" in
	"")
	    if [ "$MANPARAM" = "" ]
	    then
		man -C "$MANROOT/man.conf" -- "$COMMAND" 2>/dev/null
	    else
		man -C "$MANROOT/man.conf" $MANPARAM -- "$COMMAND" 2>&1
	    fi
	    ;;
	*)
	    man -C "$MANROOT/man.conf" -- "$SECTION" "$COMMAND" 2>/dev/null
	    ;;
	esac | \
	sed \
	    -e '1n' \
	    -e '/- *$/N
{
s/\([0-9A-z][-,0-9A-z]*\)-\n\(  *\)\([0-9A-z][-,0-9A-z]*([1-9][A-z]*)\)/\1\3\
\2/
}' \
	    -e '/- *$/N
{
s/\([0-9A-z][-,0-9A-z]*\)-\n\(  *\)\([0-9A-z][-,0-9A-z]*([1-9][A-z]*)\)/\1\3\
\2/
}' \
	    -e '/- *$/N
{
s/\([0-9A-z][-,0-9A-z]*\)-\n\(  *\)\([0-9A-z][-,0-9A-z]*([1-9][A-z]*)\)/\1\3\
\2/
}' \
	    -e '/- *$/N
{
s/\([0-9A-z][-,0-9A-z]*\)-\n\(  *\)\([0-9A-z][-,0-9A-z]*([1-9][A-z]*)\)/\1\3\
\2/
}' \
	    -e 's/</«/g' \
	    -e 's/>/»/g' \
   \
	    -e '/^[A-Z]/s/.//g' \
	    -e 's/^[A-Z][-+() ,A-Z_\/]*$/<br \/><b class="section"><a id="&" href="#&">&<\/a><\/b><br \/>/' \
   \
	    -e 's/_\(.\)/<i>\1<\/i>/g' \
	    -e 's/.\(.\)/<b>\1<\/b>/g' \
   \
	    -e 's#<i>\(.\)</i<b>\1</b>#<b>\1</b>#g' \
	    -e 's#</b><b>.##g' \
	    -e 's#</b>.<b>##g' \
	    -e 's#.##g' \
	    -e 's#_</i<b><</b>i>##g'  \
   \
	    -e 's#</i>\( *\)<i>#\1#g' \
	    -e 's#</b>\( *\)<b>#\1#g' \
   \
	    -e 's#</b><i>\(.\)</i><b>#\1#g' \
   \
	    -e 's/^  \([A-Z][ ,0-9A-z_]*\)$/  <b>\1<\/b>/' \
	    -e 's/^   \([A-Z][ ,0-9A-z_]*\)$/   <b>\1<\/b>/' \
   \
	    -e "/^  */s#\(\(<[bi]>\)*\([0-9A-z_][-.,0-9A-z_/]*\) *\(</[bi]>\)* *(\([1-9][A-z]*\))\)#<a href=\"/${COLL:+$COLL/}${ARCH:+$ARCH/}\3.\5\">\1</a>#g" \
   \
	    -e 's/\&/\&amp;/g' \
	    -e 's/«/\&lt;/g' \
	    -e 's/»/\&gt;/g' \
	    -e "s#^\(\([0-9A-z_][-0-9A-z_/]*\) *(\([1-9][A-z_]*\))\)#<a href=\"/${COLL:+$COLL/}${ARCH:+$ARCH/}\2.\3\">\1</a>#" \
	    2>/dev/null
	echo "</pre>"
    else
	cat <<END
<table class="outer"><tr><td>
<p>The manual page was not found. Try searching instead:</p>
  <table>
  <tr><td>Bing:&nbsp;</td><td><a
    href="https://bing.com/search?q=site%3A$SERVER_NAME%20$COMMAND"
    ><tt>site:$SERVER_NAME $COMMAND</tt></a>
  </td></tr>
  <tr><td>DuckDuckGo:&nbsp;</td><td><a
    href="https://duckduckgo.com/?q=site%3A$SERVER_NAME%20$COMMAND"
    ><tt>site:$SERVER_NAME $COMMAND</tt></a>
  </td></tr>
  <tr><td>Google:&nbsp;</td><td><a
    href="https://google.com/search?q=site%3A$SERVER_NAME%20$COMMAND"
    ><tt>site:$SERVER_NAME $COMMAND</tt></a>
  </td></tr>
  <tr><td>Qwant:&nbsp;</td><td><a
    href="https://qwant.com/?q=site%3A$SERVER_NAME%20$COMMAND"
    ><tt>site:$SERVER_NAME $COMMAND</tt></a>
  </td></tr>
  <tr><td>Yahoo:&nbsp;</td><td><a
    href="https://search.yahoo.com/search?p=site%3A$SERVER_NAME%20$COMMAND"
    ><tt>site:$SERVER_NAME $COMMAND</tt></a>
  </td></tr>
  <tr><td>Yandex:&nbsp;</td><td><a
    href="https://yandex.com/search/?text=site%3A$SERVER_NAME%20$COMMAND"
    ><tt>site:$SERVER_NAME $COMMAND</tt></a>
  </td></tr>
  </table>
</td></tr></table>
END

# <a href="$SCRIPT_NAME/apropos?$COMMAND$SECTION$ARCH$COLL">Try
# apropos</a> or select a different architecture.</p>
# END

    fi
else
    cat <<END
<title>${CNAME:-$OSNAME} Manual Pages</title>
<link rel="shortcut icon" href="/s/${CNAME:-$OSNAME}.ico" type="image/x-icon">
</head>
<body>
<h1><img alt="" src=$PAGES> ${CNAME:-$OSNAME} Manual Pages</h1>
<p><b>${CNAME:-$OSNAME} ${CREL:-$OSREL} (${MACHINE:-$OSARCH})</b></p>
<hr />
<table class="outer"><tr><td>
<p>Here are the intro pages of each possible section:</p>
<table class="intro">
<tr>
<td class="section">1</td>
<td><a href="$SCRIPT_NAME?intro+1${ARCH:+.$ARCH}${COLL:++$COLL}">GENERAL COMMANDS</a></td>
</tr>
<tr>
<td class="section">2</td>
<td><a href="$SCRIPT_NAME?intro+2${ARCH:+.$ARCH}${COLL:++$COLL}">SYSTEM CALLS AND ERROR NUMBERS</a></td>
</tr>
<tr>
<td class="section">3</td>
<td><a href="$SCRIPT_NAME?intro+3${ARCH:+.$ARCH}${COLL:++$COLL}">C LIBRARY FUNCTIONS</a></td>
</tr>
<tr>
<td class="section">3f</td>
<td><a href="$SCRIPT_NAME?intro+3f${ARCH:+.$ARCH}${COLL:++$COLL}">FORTRAN LIBRARY FUNCTIONS</a></td>
</tr>
<tr>
<td class="section">3lua</td>
<td><a href="$SCRIPT_NAME?intro+3lua${ARCH:+.$ARCH}${COLL:++$COLL}">LUA MODULES</a></td>
</tr>
<tr>
<td class="section">4</td>
<td><a href="$SCRIPT_NAME?intro+4${ARCH:+.$ARCH}${COLL:++$COLL}">SPECIAL FILES AND HARDWARE SUPPORT</a></td>
</tr>
<tr>
<td class="section">5</td>
<td><a href="$SCRIPT_NAME?intro+5${ARCH:+.$ARCH}${COLL:++$COLL}">FILE FORMATS</a></td>
</tr>
<tr>
<td class="section">6</td>
<td><a href="$SCRIPT_NAME?intro+6${ARCH:+.$ARCH}${COLL:++$COLL}">GAMES AND DEMOS</a></td>
</tr>
<tr>
<td class="section">7</td>
<td><a href="$SCRIPT_NAME?intro+7${ARCH:+.$ARCH}${COLL:++$COLL}">MISCELLANEOUS INFORMATION PAGES</a></td>
</tr>
<tr>
<td class="section">8</td>
<td><a href="$SCRIPT_NAME?intro+8${ARCH:+.$ARCH}${COLL:++$COLL}">SYSTEM MAINTENANCE COMMANDS</a></td>
</tr>
<tr>
<td class="section">9</td>
<td><a href="$SCRIPT_NAME?intro+9${ARCH:+.$ARCH}${COLL:++$COLL}">KERNEL INTERNALS</a></td>
</tr>
<tr>
<td class="section">9lua</td>
<td><a href="$SCRIPT_NAME?intro+9lua${ARCH:+.$ARCH}${COLL:++$COLL}">LUA KERNEL BINDINGS</a></td>
</tr>
<tr>
<td class="section">X</td>
<td><a href="$SCRIPT_NAME?X+7${ARCH:+.$ARCH}${COLL:++$COLL}">X WINDOW SYSTEM</a></td>
</tr>
</table>
<p class="small">Sometimes man pages are not stored in the right section
and you may get an empty page. Follow the link at the top of the empty page
and you'll get your man page (hopefully).</p>
</td></tr></table>
END
fi

cat <<END
<div class="queryform">
<hr />
<table class="outer"><tr><td>
<p>You can also request any man page by name and (optionally) by section:</p>
<form method=post action="$SCRIPT_NAME">
  <table>
  <tr><td>Command:&nbsp;</td><td><input name="command" size="24"
  value="$COMMAND"></td></tr>
  <tr><td>Section:&nbsp;</td><td><select name="section">
END

# XXX: Create a seclist and use that?
for i in \
    'ANY Search in All Sections' \
    '1 General Commands' \
    '2 System Calls' \
    '3 C Library Functions' \
    '3f Fortran Library Functions' \
    '3lua Lua Modules' \
    '4 Special Files and Hardware Support' \
    '5 File Formats' \
    '6 Games and Demos' \
    '7 Miscellaneous Information Pages' \
    '8 System Maintenance Commands' \
    '9 Kernel Internals' \
    '9lua Lua Kernel Bindings' \
    ;
do
    set -- ${i}
    s="${1}"
    shift
    case "$s" in
    "$SECTION")
	echo "  <option value=\"$s\" selected>$s - $@</option>"
	;;
    *)
	echo "  <option value=\"$s\">$s - $@</option>"
	;;
    esac
done

cat <<END
  </select></td></tr>
  <tr><td>Architecture:&nbsp;</td><td><select name="arch">
END

for i in $(list_archs)
do
    case "$i" in
    DEFAULT)
	echo "  <option value=\"DEFAULT\">DEFAULT ($OSARCH)</option>"
	;;
    "${ARCH}")
	echo "  <option value=\"$i\" selected>$i</option>"
	;;
    *)
	echo "  <option value=\"$i\">$i</option>"
	;;
    esac
done

cat <<END
  </select></td></tr>
  <tr><td>Collection:&nbsp;</td><td><select name="coll">
END

for i in $(list_collections)
do
    case "$i" in
    DEFAULT)
	echo "  <option value=\"$i\">$i ($OSNAME-$OSREL)</option>"
	;;
    "$COLL")
	echo "  <option value=\"$i\" selected>$i</option>"
	;;
    *)
	echo "  <option value=\"$i\">$i</option>"
	;;
    esac
done

cat <<END
  </select></td></tr>
  <tr><td>&nbsp;</td>
  <td><input type="submit" value="Show manual page"></td></tr>
  </table>
END

case "${DEFAULT_COLLECTION}" in
"")
    cat <<END
  <p>Use the DEFAULT collection to view manual pages
  for third-party software.</p>
END
    ;;
esac

cat <<END
</form>
</td></tr></table>
<hr />
</div>
<address class="small">
Powered by man-cgi 1.15, Panagiotis Christias<br />
Modified for <a href="${REQUEST_SCHEME-:http}://www.netbsd.org/">NetBSD</a>
    by <a href="https://kimmo.suominen.com/">Kimmo Suominen</a>
</address>
<script><!--
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
 ga('create', 'UA-39862532-1', 'gw.com');
 ga('send', 'pageview');
// --></script>
</body>
</html>
END
exit 0
